apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes=hostPath --stdout
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: grafana
      name: grafana
    spec:
      ports:
        - name: "3000"
          port: 3000
          targetPort: 3000
      selector:
        io.kompose.service: grafana
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes=hostPath --stdout
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: prometheus
      name: prometheus
    spec:
      ports:
        - name: "9090"
          port: 9090
          targetPort: 9090
      selector:
        io.kompose.service: prometheus
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes=hostPath --stdout
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: grafana
      name: grafana
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: grafana
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert --volumes=hostPath --stdout
            kompose.version: 1.27.0 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.service: grafana
        spec:
          containers:
            - image: grafana/grafana
              name: grafana
              ports:
                - containerPort: 3000
              resources: {}
          hostname: grafana
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes=hostPath --stdout
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: prometheus
      name: prometheus
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: prometheus
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert --volumes=hostPath --stdout
            kompose.version: 1.27.0 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.service: prometheus
        spec:
          containers:
            - args:
                - --config.file=/etc/prometheus/prometheus.yml
              image: prom/prometheus
              name: prometheus
              ports:
                - containerPort: 9090
              resources: {}
          hostname: prometheus
          restartPolicy: Always
    status: {}
kind: List
metadata: {}
